### ISSUE TITLE
Empty SauceLabs Plugin Tab

### ISSUE THREAD

**Issue by SenhorCastor** [rossrowe/sauce-teamcity-plugin#14]
SLabs Plugin: 1.30
TC Version: TeamCity Enterprise 9.0.3 (build 32334)

I am printing in the output stream:

SauceOnDemandSessionID=135bc467b43941da9570a1b3058fc4a8 job-name=Web:3962824889:c.r.w.t.IntegrationSetupTests:mailChimpIntegration

The job exists in SauceLabs, but the SauceLabs Plugin Tab is empty. This started happening a while ago, but I was waiting to upgrade to V1.30 to make sure it wasn't me that I was using an outdated version

![sltc03](https://cloud.githubusercontent.com/assets/3718999/6899993/adf03930-d6b8-11e4-88af-052f8107c6a1.png)

![sltc02](https://cloud.githubusercontent.com/assets/3718999/6899989/a6b0b640-d6b8-11e4-9b87-4e9717d9ef0f.png)

![sltc01](https://cloud.githubusercontent.com/assets/3718999/6899981/9b7a0bf0-d6b8-11e4-8952-dea5d2037f0d.png)

**Comment by rossrowe** [comment]
Thanks for letting me know, I'll try replicate the problem in my environment and I'll let you know what I find

**Comment by rossrowe** [comment]
Hi, it looks like the Sauce REST API call that the plugin is issuing (https://saucelabs.com/rest/v1/your_user_name/build/your_build_number/jobs) isn't returning any results.  As you mentioned, this looks like it's a recent change at the Sauce Labs end, rather than being due to a change in the plugin.  Would you mind raising a support issue with Sauce Labs so that they can take a look at it?

**Comment by SenhorCastor** [comment]
Yeah I will do it. Thanks for the quick response!

**Comment by SenhorCastor** [comment]
Hi Ross,

I am looking at the Documentation online of SauceLabs, and I dont see that
call anyway

I see *https://saucelabs.com/rest/v1/saucelabs_relateiq/jobs?full
<https://saucelabs.com/rest/v1/saucelabs_relateiq/jobs?full>**=**true and*

*https://saucelabs.com/rest/v1/saucelabs_relateiq/jobs/YOUR_JOB_ID
<https://saucelabs.com/rest/v1/saucelabs_relateiq/jobs/YOUR_JOB_ID>*

I am missing something?


Thanks

Fernando

**Comment by rossrowe** [comment]
Yeah, that call wasn't included in the documentation but was created by Sauce Labs to cater for the CI plugins - they're taking a look into the issue now, hopefully it'll be resolved soon.

**Comment by SenhorCastor** [comment]
Oh, my bad. Didn't want to jump into reporting something that I didn't
quite understand.

Thanks again!

**Comment by SenhorCastor** [comment]
Any updates on your side? I submitted a request a week ago and I got:

This is a bug in the way Team City access the rest API for Sauce Labs and is being looked at by our developers. We are in a holding pattern at the moment and I will update when the issue is resolved. However, should you have any additional questions on this topic in the meantime then please feel free to ask.

**Comment by rossrowe** [comment]
Hi Fernando, apologies for the ongoing inconvenience, I believe that a fix
has been developed on the Sauce REST API side, but I don't know when it's
scheduled for release - I'll try to find out a date and I'll get back to you

**Comment by SenhorCastor** [comment]
No worries! thanks for the update and for the plugin.

**Comment by rossrowe** [comment]
Hi again, would you be able to try run a new build and view the results tab
in TeamCity?  The Sauce guys have released a fix for the change, and as far
as I can tell, it seems to be working okay for new builds

**Comment by SenhorCastor** [comment]
Working,

Thanks Ross,

Fernando
