### ISSUE TITLE
Saucelabs Results tab is empty (node)

### ISSUE THREAD

**Issue by mekdev** [rossrowe/sauce-teamcity-plugin#15]
Hi guys,
I am running into the same issue as Its the same issue as https://github.com/rossrowe/sauce-teamcity-plugin/issues/14 but using NodeJs and Selenium-Webdriver
Saucelabs plugin 1.32
Framework : Mocha

I am outputting the session via console.log, have also tried wrapping the test name in quotes and not

```
console.log('SauceOnDemandSessionID=' + sessionId +  ' job-name="'+ currentTest.title +'"');

 SauceOnDemandSessionID=3477c879e3e14c0ca0082d90e621bd18 job-name="should beable to create a job with square geofence"
```

![screen shot 2015-07-28 at 3 14 09 pm](https://cloud.githubusercontent.com/assets/2752830/8945356/8cbe26a0-353b-11e5-8713-be3478afee58.png)
![screen shot 2015-07-28 at 3 05 34 pm](https://cloud.githubusercontent.com/assets/2752830/8945357/8cc19a1a-353b-11e5-9df2-583e53d26bbc.png)

But the results tab in teamcity is empty the summary also does not show any test result.

![screen shot 2015-07-28 at 3 17 38 pm](https://cloud.githubusercontent.com/assets/2752830/8945401/f3157a2a-353b-11e5-91d2-9883bde9de69.png)

The session and name exists in saucelabs
![screen shot 2015-07-28 at 3 18 01 pm](https://cloud.githubusercontent.com/assets/2752830/8945453/600c6ecc-353c-11e5-805e-233b568dd233.png)

Any help with this is very appreciated.

**Comment by rossrowe** [comment]
Hi, would you be able to try set the 'build' capability to the value of the
SAUCE_TC_BUILDNUMBER environment variable, eg.

capabilities.setCapability("build", System.getenv("SAUCE_TC_BUILDNUMBER"));

then run a new build to see if the embedded report is displayed?

**Comment by mekdev** [comment]
Good morning @rossrowe !

Yes I confirm this is needed. 
Added `process.env.SAUCE_TC_BUILDNUMBER` 
In my driver factory I am now building the following

```
    {
        browserName: capability.browserName,
        platform: capability.platform,
        username: username,
        accessKey: key,
        name : 'Saucelabs test',
        screenResolution : resolution,
        build: process.env.SAUCE_TC_BUILDNUMBER
    }
```

Thank you!
